### PR TITLE
Mastery Exercise Submission

### PR DESCRIPTION
**Pull request by jackmoch**

### CODE REVIEW

**Comment by jackmoch** [comment]
@c-stein hey, I hope this works!!!!

**Comment by C-Stein** [comment]
Nice work @jackmoch. It's obvious that you know what's going on and understand the concepts at work. Two tweaks to make before you merge...
1- You're currently limiting the results to 9 instead of 10
2- The is a usage message in some of your commits, but it didn't make it into the final product

Let me know if you have any questions

**Comment by jackmoch** [comment]
@C-Stein added that usage statement back in and changed my limit function! Let me know if you see anything else I need to touch up!

**Comment by C-Stein** [comment]
👍

**Pull request merged**
